# fly.toml app configuration file generated for app-summer-frost-8316 on 2024-10-20T14:32:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-summer-frost-8316'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
